project:
  type: website
  output-dir: docs
  
website:
  title: "Robison"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - Research.qmd
      - Publications.qmd
      - text: "Teaching"
        file: Teaching.qmd
      - PolymorphicGames.qmd
      - text: "BLOG"
        file: ProfessorPolymorphic/index.qmd

  sidebar:
   contents: auto

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

