<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.203">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Barrie Robison, Michael Overton">
<meta name="dcterms.date" content="2023-01-12">

<title>Robison - CERTIFICATE</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Robison</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html">
 <span class="menu-text">HOME</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../../Research.html" aria-current="page">
 <span class="menu-text">RESEARCH</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../Publications.html">
 <span class="menu-text">PUPBLICATIONS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../Teaching.html">
 <span class="menu-text">TEACHING</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../PolymorphicGames.html">
 <span class="menu-text">STUDIO</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../ProfessorPolymorphic/index.html">
 <span class="menu-text">BLOG</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Certificate</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title d-none d-lg-block">Certificate</h1>
            <p class="subtitle lead">BCB 504 / 520</p>
                                <div class="quarto-categories">
                <div class="quarto-category">Resources</div>
                <div class="quarto-category">Education</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Barrie Robison, Michael Overton </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 12, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../about.html" class="sidebar-item-text sidebar-link">About</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PolymorphicGames.html" class="sidebar-item-text sidebar-link">Polymorphic Games</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../Publications.html" class="sidebar-item-text sidebar-link">PUBLICATIONS</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../Research.html" class="sidebar-item-text sidebar-link">RESEARCH</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../Teaching.html" class="sidebar-item-text sidebar-link">TEACHING</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">BCB520</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/BCB520.html" class="sidebar-item-text sidebar-link">BCB 520 :: Foundations of Data Visualization</a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Posts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/A1-Lit-Prog/index.html" class="sidebar-item-text sidebar-link">ASSIGNMENT 1 - Fun with literate programming.</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/Certificate/index.html" class="sidebar-item-text sidebar-link active">CERTIFICATE</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/L1-Intro/index.html" class="sidebar-item-text sidebar-link">LECTURE 1 - INTRO</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/L2-Data-Abstraction/index.html" class="sidebar-item-text sidebar-link">LECTURE 2 - DATA ABSTRACTION</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/Syllabus/index.html" class="sidebar-item-text sidebar-link">SYLLABUS 2023</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/T1-Lit-Prog/index.html" class="sidebar-item-text sidebar-link">TUTORIAL 1 - Literate Programming</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/T2-Anscombe/index.html" class="sidebar-item-text sidebar-link">TUTORIAL 2 - Literate Programming and Anscombe’s Quartet</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../BCB520/posts/T3-Python/index.html" class="sidebar-item-text sidebar-link">TUTORIAL 3 - Python</a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ProfessorPolymorphic/index.html" class="sidebar-item-text sidebar-link">Professor Polymorphic</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/about.html" class="sidebar-item-text sidebar-link">About</a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">Posts</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/posts/post-with-code/index.html" class="sidebar-item-text sidebar-link">Observable Experiment</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/posts/UndergradResearch/index.html" class="sidebar-item-text sidebar-link">UNDERGRADUATE RESEARCH</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/posts/welcome/index.html" class="sidebar-item-text sidebar-link">You’ve gotta be f***ing kidding…</a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ProfessorPolymorphic/posts/LabMeetingJan20/index.html" class="sidebar-item-text sidebar-link">Polymorphic Games Lab Meeting</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/posts/LabMeetingJan20/OSTime.html" class="sidebar-item-text sidebar-link">OSDevTimeline</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ProfessorPolymorphic/posts/LabMeetingJan20/SanteFeWorkshop.html" class="sidebar-item-text sidebar-link">SanteFe Workshop</a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#professional-applications-in-data-science" id="toc-professional-applications-in-data-science" class="nav-link active" data-scroll-target="#professional-applications-in-data-science"><strong>PROFESSIONAL APPLICATIONS IN DATA SCIENCE</strong></a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><strong>OVERVIEW</strong></a>
  <ul class="collapse">
  <li><a href="#the-university-of-idahos-value-proposition-for-a-certificate-in-the-professional-applications-in-data-science" id="toc-the-university-of-idahos-value-proposition-for-a-certificate-in-the-professional-applications-in-data-science" class="nav-link" data-scroll-target="#the-university-of-idahos-value-proposition-for-a-certificate-in-the-professional-applications-in-data-science"><strong>The University of Idaho’s value proposition for a certificate in the Professional Applications in Data Science:</strong></a></li>
  <li><a href="#intended-audience" id="toc-intended-audience" class="nav-link" data-scroll-target="#intended-audience">Intended Audience:</a></li>
  <li><a href="#student-learning-outcomes" id="toc-student-learning-outcomes" class="nav-link" data-scroll-target="#student-learning-outcomes">Student Learning Outcomes:</a></li>
  </ul></li>
  <li><a href="#curriculum" id="toc-curriculum" class="nav-link" data-scroll-target="#curriculum">CURRICULUM</a>
  <ul class="collapse">
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites:</a></li>
  <li><a href="#certificate-requirements-12-credits-total" id="toc-certificate-requirements-12-credits-total" class="nav-link" data-scroll-target="#certificate-requirements-12-credits-total">Certificate Requirements (12 Credits Total)</a></li>
  <li><a href="#course-descriptions" id="toc-course-descriptions" class="nav-link" data-scroll-target="#course-descriptions">Course Descriptions</a></li>
  </ul></li>
  <li><a href="#governance-and-administration" id="toc-governance-and-administration" class="nav-link" data-scroll-target="#governance-and-administration">GOVERNANCE AND ADMINISTRATION</a>
  <ul class="collapse">
  <li><a href="#administrative-home" id="toc-administrative-home" class="nav-link" data-scroll-target="#administrative-home">Administrative Home</a></li>
  <li><a href="#governance-and-oversight" id="toc-governance-and-oversight" class="nav-link" data-scroll-target="#governance-and-oversight">Governance and Oversight</a></li>
  </ul></li>
  <li><a href="#general-university-requirements" id="toc-general-university-requirements" class="nav-link" data-scroll-target="#general-university-requirements">GENERAL UNIVERSITY REQUIREMENTS</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>A graduate certificate that trains non-specialists how to think about, organize, analyze, and visualize data, and communicate data-driven insights to technical and lay audiences.</p>
<section id="professional-applications-in-data-science" class="level1">
<h1><strong>PROFESSIONAL APPLICATIONS IN DATA SCIENCE</strong></h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview"><strong>OVERVIEW</strong></h2>
<p>We live in an increasingly data-driven world. Basic data literacy and data science skills are becoming central to virtually every industry. Yet, limited opportunities exist to gain these skills without an advanced background in math and computer science. To address this workforce development need, we propose a competitively valued on-line graduate certificate in the Professional Applications in Data Science. The certificate is designed to offer rigorous training in the foundations of data science to anyone with a bachelor’s degree. Participants will learn how to think about, organize, analyze, and visualize data, and communicate data driven insights to diverse audiences. The curriculum emphasizes the use of data sets drawn from each student’s individual discipline, aligning the certificate’s workforce development impacts with the University of Idaho’s land grant mission.</p>
<section id="the-university-of-idahos-value-proposition-for-a-certificate-in-the-professional-applications-in-data-science" class="level3">
<h3 class="anchored" data-anchor-id="the-university-of-idahos-value-proposition-for-a-certificate-in-the-professional-applications-in-data-science"><strong>The University of Idaho’s value proposition for a certificate in the Professional Applications in Data Science:</strong></h3>
<p>The graduate certificate in Professional Applications in Data Science will provide unique value to UI constituencies by:</p>
<ol type="1">
<li><p>Aligning data science training with fields of nascent demand that are part of our land grant mission, including Agriculture, Natural Resources, and Education.</p></li>
<li><p>Requiring a digital data science portfolio with which students can demonstrate their proficiencies to potential employers.</p></li>
<li><p>Emphasizing training in data communication - including verbal presentation and data visualization - two components of data science that are underrepresented in competing certificates.</p></li>
<li><p>Filling a growing workforce development gap by offering a unique data science certificate that is appropriate for professionals with a bachelor’s degree who do not have a rigorous background in mathematics, statistics, or computer science.</p></li>
</ol>
</section>
<section id="intended-audience" class="level3">
<h3 class="anchored" data-anchor-id="intended-audience">Intended Audience:</h3>
<p>This certificate leverages the University of Idaho’s interdisciplinary culture to provide integrative training in the foundations of data science. It is intended for:</p>
<ol type="1">
<li><p>Working professionals with a bachelor’s degree whose career increasingly involves the generation, management, analysis, and visualization of large data sets. The certificate is appropriate for professionals in STEM fields, Health Care, Business, Government, Education, Journalism, Athletics, Natural Resources, and Agriculture.</p></li>
<li><p>Graduate students in programs outside of the core technical disciplines of data science (statistics, math, engineering, or computer science). The certificate will complement disciplinary research methods courses with training in data management, visualization, and communication.</p></li>
<li><p>Undergraduates at the UI who wish to incorporate data science training into their degree and graduate with a Bachelor’s degree and a graduate certificate.</p></li>
</ol>
</section>
<section id="student-learning-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="student-learning-outcomes">Student Learning Outcomes:</h3>
<p>Upon completion of the certificate, students will be able to:</p>
<p>* Use open-source software to reproducibly manage, analyze, and visualize large, complex, and noisy data sets.</p>
<p>* Practice high quality and ethical data stewardship.</p>
<p>* Understand and execute data exploration.</p>
<p>* Effectively communicate data driven insights to experts and non-experts.</p>
<p>* Demonstrate their skills with an online portfolio of analyses and visualizations relevant to their field of specialization.</p>
</section>
</section>
<section id="curriculum" class="level2">
<h2 class="anchored" data-anchor-id="curriculum">CURRICULUM</h2>
<section id="prerequisites" class="level3">
<h3 class="anchored" data-anchor-id="prerequisites">Prerequisites:</h3>
<p>A Bachelor’s degree OR the student has senior standing and is enrolled in a bachelor’s degree program at the University of Idaho.</p>
</section>
<section id="certificate-requirements-12-credits-total" class="level3">
<h3 class="anchored" data-anchor-id="certificate-requirements-12-credits-total">Certificate Requirements (12 Credits Total)</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 10%">
<col style="width: 29%">
<col style="width: 6%">
<col style="width: 28%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Course</th>
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Credits</th>
<th style="text-align: left;">Prerequisites</th>
<th style="text-align: left;">Schedule</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INTR 509</td>
<td style="text-align: left;">Introduction to Applied Data Science</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">BS degree or permission</td>
<td style="text-align: left;">Spring and asynchronous online</td>
</tr>
<tr class="even">
<td style="text-align: left;">BCB 5xx</td>
<td style="text-align: left;">Communicating with Data</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">INTR 509 or BS degree or permission</td>
<td style="text-align: left;">Spring and asynchronous online</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BCB 5xx</td>
<td style="text-align: left;">Data Visualization</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 251 or INTR 509 or permission</td>
<td style="text-align: left;">Fall and asynchronous online</td>
</tr>
<tr class="even">
<td style="text-align: left;">BCB 5xx</td>
<td style="text-align: left;">Data Science Portfolio</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">INTR 509 and BCB 520 (Data Viz)</td>
<td style="text-align: left;">Asynchronous online</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Elective</strong></td>
<td style="text-align: left;">Varies</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Varies</td>
<td style="text-align: left;">Varies</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>*note: Courses designated with “BCB 5XX” are new courses that will be offered in the 2023-24 academic year*</p>
</section>
<section id="course-descriptions" class="level3">
<h3 class="anchored" data-anchor-id="course-descriptions">Course Descriptions</h3>
<section id="intr-509-introduction-to-applied-data-science-3-credits" class="level4">
<h4 class="anchored" data-anchor-id="intr-509-introduction-to-applied-data-science-3-credits">INTR 509 Introduction to Applied Data Science (3 credits)</h4>
<p>*In person (spring) and asynchronous online.*</p>
<p>Students are provided a foundation for “thinking with data” through the introduction of computational, statistical, and data literacy skills. This includes the selection, collection, cleaning, management, descriptive analysis, and exploratory analysis of a dataset unique to their professional interests using modern computing languages. This course is taught by Dr.&nbsp;Michael Overton.</p>
</section>
<section id="bcb-5xx-communicating-with-data-2-credits" class="level4">
<h4 class="anchored" data-anchor-id="bcb-5xx-communicating-with-data-2-credits">BCB 5XX Communicating with Data (2 credits)</h4>
<p>*In person (spring) and asynchronous online.*</p>
<p>Students are taught writing and presentation skills to improve their communication of data-driven insights to specialist and lay audiences. The course emphasizes reproducible research practices, including literate programming (R Markdown) and version control (GitHub). Course content includes the conceptual foundations of communicating with data along with written and verbal communication assignments using data sets individualized to each student’s interest. This course will be taught by Dr.&nbsp;Barrie Robison.</p>
<p>Text: Nolan and Stoudt. 2021. Communicating with data: The art of writing for data science. Oxford University Press.</p>
<p>Prerequisites: INTR 509 OR A BS degree OR permission.</p>
<p>*Note: This course could be divided into two 1 credit modules (verbal and written communication) which may facilitate online delivery and movement toward a stacking microcredential model.*</p>
</section>
<section id="bcb-5xx-data-visualization-3-credits" class="level4">
<h4 class="anchored" data-anchor-id="bcb-5xx-data-visualization-3-credits">BCB 5XX Data Visualization (3 credits)</h4>
<p>*In person (fall) and asynchronous online*</p>
<p>This course covers the conceptual foundations of data visualization and design. Students will learn how visualization design choices related to marks and channels, color, and spatial arrangement interact with the human perceptual system. The course considers tabular, network, and spatial data, and students will implement visualizations in R.</p>
<p>Text: Munzner. 2014. Visualization Analysis &amp; Design. CRC Press.</p>
<p>Prerequisites: INTR 509 OR A BS degree OR Stat 251 OR Permission.</p>
<p>*Note: This course could be divided into three 1 credit modules (Foundations, Tabular Data, Advanced Topics) which may facilitate online delivery and movement toward a stacking microcredential model.*</p>
</section>
<section id="bcb-5xx-online-portfolio-1-credit" class="level4">
<h4 class="anchored" data-anchor-id="bcb-5xx-online-portfolio-1-credit">BCB 5XX Online Portfolio (1 credit)</h4>
<p>*Asynchronous online*</p>
<p>This course provides feedback, review, and approval of the student’s online data science portfolio. This portfolio is intended to represent the body of work accumulated by the student over the course of the certificate. It should contain examples of novel data products (such as FAIR data sets), analyses, and visualizations. All elements of the portfolio will be hosted online (likely in a GitHub repository or professional website), be open source, and demonstrate best practices of literate programming and reproducible research. This course will be taught by Dr.&nbsp;Barrie Robison.</p>
</section>
<section id="electives" class="level4">
<h4 class="anchored" data-anchor-id="electives">Electives:</h4>
<p>The certificate allows each student to customize their training by choosing a 3-credit graduate elective.</p>
<p>For students seeking foundational training who have not already taken Stat 431 or its equivalent, <strong><em>we recommend Stat 431 or a 3-credit graduate level disciplinary research methods course</em></strong>.</p>
<p>For students seeking to add the certificate to an existing degree at UI, or students who already have some advanced technical training, additional electives are possible. Note that many of these optional electives have substantial disciplinary pre-requisites. Not all electives are available in an online format.</p>
</section>
<section id="choose-one-of-the-following" class="level4">
<h4 class="anchored" data-anchor-id="choose-one-of-the-following">Choose one of the following:</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Course</th>
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Credits</th>
<th style="text-align: left;">Prerequisites</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=AVS%20531">AVS 531</a></td>
<td style="text-align: left;">Practical Methods in Analyzing Animal Science Experiments</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">400-level statistics course</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BE%20521">BE 521</a></td>
<td style="text-align: left;">Image Processing and Computer Vision</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">(BE 242 and MATH 275) or permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BE%20541">BE 541</a></td>
<td style="text-align: left;">Instrumentation and Measurements</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ENGR 240; Coreqs: STAT 301</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BIOL%20526">BIOL 526</a></td>
<td style="text-align: left;">Systems Biology</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">(BIOL&nbsp;115,&nbsp;BIOL&nbsp;115L&nbsp;and&nbsp;MATH&nbsp;170)&nbsp;or permission of instructor</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BIOL%20545">BIOL 545</a></td>
<td style="text-align: left;">Phylogenetics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">PLSC 205 or BIOL 213 and BIOL 310</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BIOL%20549">BIOL 549</a></td>
<td style="text-align: left;">Computer Skills for Biologists</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">BIOL 310 and STAT 251 or STAT 301; or Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=BIOL%20563">BIOL 563</a></td>
<td style="text-align: left;">Mathematical Genetics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH 160 or MATH 170 and STAT 251 or STAT 301</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CE%20526">CE 526</a></td>
<td style="text-align: left;">Aquatic Habitat Modeling</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">A minimum grade of ‘C’ or better is required for all pre/corequisites; Prereqs: CE 322 and CE 325 or BE 355; or Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CE%20579">CE 579</a></td>
<td style="text-align: left;">Simulation of Transportation Systems</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20511">CS 511</a></td>
<td style="text-align: left;">Parallel Programming</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CS 395</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20574">CS 574</a></td>
<td style="text-align: left;">Deep Learning</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">(CS&nbsp;121&nbsp;or&nbsp;MATH&nbsp;330) and&nbsp;STAT&nbsp;301</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20570">CS 570</a></td>
<td style="text-align: left;">Artificial Intelligence</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CS&nbsp;210</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20572">CS 572</a></td>
<td style="text-align: left;">Evolutionary Computation</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CS&nbsp;211</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20575">CS 575</a></td>
<td style="text-align: left;">Machine Learning</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CS 210</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20577">CS 577</a></td>
<td style="text-align: left;">Python for Machine Learning</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">(CS&nbsp;121&nbsp;or&nbsp;MATH&nbsp;330) and&nbsp;STAT&nbsp;301</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20578">CS 578</a></td>
<td style="text-align: left;">Neural Network Design</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20579">CS 579</a></td>
<td style="text-align: left;">Data Science</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH&nbsp;330&nbsp;or Permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CS%20589">CS 589</a></td>
<td style="text-align: left;">Semantic Web and Open Data</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CS&nbsp;360&nbsp;or&nbsp;CS&nbsp;479&nbsp;or&nbsp;CS&nbsp;579</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CTE%20519">CTE 519</a></td>
<td style="text-align: left;">Database Applications and Information Management</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=CYB%20520">CYB 520</a></td>
<td style="text-align: left;">Digital Forensics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">CYB 310</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20571">ED 571</a></td>
<td style="text-align: left;">Introduction to Quantitative Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Graduate standing</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20584">ED 584</a></td>
<td style="text-align: left;">Univariate Quantitative Research in Education</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ED 571</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20587">ED 587</a></td>
<td style="text-align: left;">Multivariate Quantitative Analysis in Education</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ED 584 or Permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20589">ED 589</a></td>
<td style="text-align: left;">Theoretical Applications and Designs of Qualitative Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ED 574 or Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20590">ED 590</a></td>
<td style="text-align: left;">Data Analysis and Interpretation of Qualitative Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ED 574 and ED 589</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20591">ED 591</a></td>
<td style="text-align: left;">Indigenous and Decolonizing Research Methods</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20592">ED 592</a></td>
<td style="text-align: left;">Decolonizing, Indigenous, and Action-Based Research Methods</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ED%20595">ED 595</a></td>
<td style="text-align: left;">Survey Design for Social Science Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Recommended Preparation: Foundations of Research course at graduate level.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=EDAD%20570">EDAD 570</a></td>
<td style="text-align: left;">Methods of Educational Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ENT%20504">ENT 504</a></td>
<td style="text-align: left;">Applied Bioinformatics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ENVS%20511">ENVS 511</a></td>
<td style="text-align: left;">Data Wizardry in Environmental Sciences</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 251</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=ENVS%20551">ENVS 551</a></td>
<td style="text-align: left;">Research Methods in the Environmental Social Sciences</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">One course or experience in basic statistics or Instructor Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=FOR%20514">FOR 514</a></td>
<td style="text-align: left;">Forest Biometrics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431 or equivalent</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=FOR%20535">FOR 535</a></td>
<td style="text-align: left;">Remote Sensing of Fire</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">FOR 375 or permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=GEOG%20507">GEOG 507</a></td>
<td style="text-align: left;">Spatial Statistics and Modeling</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431 or permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=GEOG%20583">GEOG 583</a></td>
<td style="text-align: left;">Remote Sensing/GIS Integration</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Coreqs: GEOG 385 or equivalent.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=Math%20538">Math 538</a></td>
<td style="text-align: left;">Stochastic Models</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH&nbsp;451&nbsp;or Permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=MIS%20555">MIS 555</a></td>
<td style="text-align: left;">Data Management for Big Data</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=NRS%20578">NRS 578</a></td>
<td style="text-align: left;">Lidar and optical remote sensing analysis using open-source software</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT251 &amp; WLF370 or STAT427 and NRS/FOR 472 or equivalent/instructor permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=POLS%20558">POLS 558</a></td>
<td style="text-align: left;">Research Methods for Local Government and Community Administration</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 251</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=REM%20507">REM 507</a></td>
<td style="text-align: left;">Landscape and Habitat Dynamics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Permission; Recommended Preparation: courses in ecology, statistics, and GIS.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=Stat%20431">Stat 431</a></td>
<td style="text-align: left;">Statistical Analysis</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT&nbsp;251&nbsp;or&nbsp;STAT&nbsp;301</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=STAT%20514">STAT 514</a></td>
<td style="text-align: left;">Nonparametric Statistics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=STAT%20516">STAT 516</a></td>
<td style="text-align: left;">Applied Regression Modeling</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=Stat%20517">Stat 517</a></td>
<td style="text-align: left;">Statistical Learning and Predictive Modeling</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=Stat%20519">Stat 519</a></td>
<td style="text-align: left;">Multivariate Analysis</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT&nbsp;431&nbsp;or equivalent.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=STAT%20535">STAT 535</a></td>
<td style="text-align: left;">Introduction to Bayesian Statistics</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">STAT 431</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=STAT%20555">STAT 555</a></td>
<td style="text-align: left;">Statistical Ecology</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH 451 or Permission</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=Stat%20565">Stat 565</a></td>
<td style="text-align: left;">Computer Intensive Methods</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">&nbsp;STAT&nbsp;451,&nbsp;STAT&nbsp;452,&nbsp;MATH&nbsp;330, and computer programming experience or Permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=WLF%20552">WLF 552</a></td>
<td style="text-align: left;">Ecological Modeling</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH 175 and FOR 221 or Permission.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=WLF%20555">WLF 555</a></td>
<td style="text-align: left;">Statistical Ecology</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MATH 451 or permission</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://catalog.uidaho.edu/search/?P=WR%20552">WR 552</a></td>
<td style="text-align: left;">Water Economics and Policy</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">AGEC 301 or AGEC 302, or ECON 351 or ECON 352, or by permission</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="governance-and-administration" class="level2">
<h2 class="anchored" data-anchor-id="governance-and-administration">GOVERNANCE AND ADMINISTRATION</h2>
<section id="administrative-home" class="level3">
<h3 class="anchored" data-anchor-id="administrative-home">Administrative Home</h3>
<p>Data Science is an applied field of study combining insights and techniques from multiple disciplines such as statistics, computer science, informatics, and social sciences. To maintain the interdisciplinary focus of the program, we propose housing the Professional Applications in Data Science certificate in the Bioinformatics and Computational Biology Program within the College of Science. Three of the required courses that will be created will use the BCB prefix. In addition, the BCB Administration (Director and Governing Board) and faculty are drawn from almost every College at the UI and are routinely called upon to consider curriculum and training from an interdisciplinary perspective.</p>
</section>
<section id="governance-and-oversight" class="level3">
<h3 class="anchored" data-anchor-id="governance-and-oversight">Governance and Oversight</h3>
<p>The BCB Director, governing board, and faculty would have curricular control over the certificate content.</p>
<p>We recommend that the BCB Director or the Dean of the College of Science appoint a faculty coordinator for the certificate in Professional Applications in Data Science. The faculty coordinator will be responsible for guiding the certificate through curriculum approvals, helping recruit students, assessment, and coordinating with faculty who teach the included courses.</p>
<p>A subcommittee within BCB could also be appointed to help maintain the certificate’s interdisciplinary focus and broad domain impact.</p>
</section>
</section>
<section id="general-university-requirements" class="level2">
<h2 class="anchored" data-anchor-id="general-university-requirements">GENERAL UNIVERSITY REQUIREMENTS</h2>
<p>In addition to the requirements specified in this document, the certificate would be subject to all UI Policies regarding <a href="https://www.uidaho.edu/registrar/faculty/curriculum">Graduate Certificates</a>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>