---
title: "BCB 521"
subtitle: "Communicating with Data"
---

BCB 521 is a core requirement of our graduate certificate: Professional Applications of Data Science. A detailed description of the certificate can be found [here](Resources/Certificate/index.qmd). The official description and course requirements of the certificate can be found [here](https://www.uidaho.edu/sci/bcb/degrees/certificate).

# Course Description

Many of the most common applications of modern data science are ultimately intended to influence, persuade, or inform other people. No matter the format and complexity of the data driven insight or result, your goal cannot be achieved unless you can effectively communicate your intended message to your audience.

This class is designed to teach students how to communicate data driven insights to a wide variety of audiences. The course considers best practices for writing about data, including approaches for scientific manuscripts, technical reports, online media, and the growing discipline of "Data Journalism". We will also cover approaches related to communicating data during verbal presentations in a variety of contexts, including scientific conferences, seminars, education, and online video formats. Finally, the course will cover (and use) some of the tools that are central to reproducible research in data science, including version control using GitHub and literate programming.

Assignments are designed so that students may use their own data or data from their discipline or industry. At least two assignments are designed to be appropriate submissions to a student's online Data Science Portfolio and can be used to satisfy the requirements of BCB 522.

The grading scheme and schedule for the course can be found in the [Syllabus](Syllabus.qmd).

The assignments for the course can be found in the [Assignments](Assignments/index.qmd) section.

The resources for the course can be found in the [Resources](Resources/index.qmd) section.

# TOPICS

The main topic areas of this course are listed here. I'll add descriptions and links to course components as we proceed through the semester.

## TOOLS FOR REPRODUCIBLE DATA SCIENCE

### VERSION CONTROL

### LITERATE PROGRAMMING

## DATA DRIVEN COMMUNICATION

### WRITING ABOUT DATA

### SPEAKING ABOUT DATA
