project:
  type: website
  output-dir: docs

website:
  title: "Professor Polymorphic"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    left:
      - href: ../index.qmd
        text: HOME
      - text: "RESEARCH"
        file: ../Research.qmd
      - text: "PUBLICATIONS"
        file: ../Publications.qmd
      - text: "TEACHING"
        file: ../Teaching.qmd
      - text: "STUDIO"
        file: ../PolymorphicGames.qmd
      - text: "BLOG"
        file: ProfessorPolymorphic/index.qmd

  sidebar:
   contents: auto
        
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

