---
title: "SanteFe Workshop"
draft: true
---

## INVITATION

Dear Dr. Robison,
 
We hope this email finds you well! On behalf of the Santa Fe Institute and the University of Texas, it is our honor to invite you to participate in a workshop on Simulation Games for Global Pandemic Resilience, which will take place at the Santa Fe Institute, in Santa Fe, New Mexico, May 17-18, 2023. All participants of the workshop will be offered support for economy travel and will be provided with local lodging in Santa Fe.
 
This workshop is funded by a new NSF program on Predictive Intelligence for Pandemic Preparedness and organized by Lauren Ancel Meyers (University of Texas at Austin), Francesca de Rosa (Center for Advanced Pathogen Threat and Response Simulation), and Margaret Polski (US Naval War College). The COVID-19 pandemic revealed catastrophic failures of imagination, preparation, and decision making by world leaders, global health organizations, and scientists. We hypothesize that preparedness exercises––drawing from military wargaming, cognitive sciences, and complex systems, and capturing the interdependencies of biological, sociological and environmental systems––can advance individual and collective decision making. Such simulations can provide essential intuition and collaborative problem solving skills for tackling uncertain threats, while elucidating human decision making, including the impacts of unforeseen events, the influences of various kinds of information, and the development of automated decision-support tools.
 
This in-person two-day workshop will convene scientists, engineers, public health experts, and military game designers to envision the application of simulation gaming to advance global preparedness for uncertain pathogen threats. We will survey the state-of-the art in gaming science and explore the development of simulation-based games that:
 
improve individual and collaborative decision making in the face of uncertain pathogen threats
enable the design of robust pathogen-related threat surveillance, prevention and response systems
elucidate cognitive and behavioral processes that drive human responses to pathogen threats.
 
Through a combination of expert panels and provocative breakout discussions, we aim to articulate a 5-10 year research agenda for advancing the art and science of simulation gaming for global threat resilience. We believe that you would bring invaluable perspectives to this effort!
 
We invite you to participate in the full two-day workshop and help us frame the conversation by speaking and sharing your epidemic simulation game in a panel on Modeling Uncertain Pathogens Threats and Cascading Global Effects.